In [1]:
import pandas as pd

df = pd.read_excel(
    r"C:\Users\ka843\Coding\Ruppee-Instability-Dashboard-and-pridictor\data\raw\cpi_1133.xlsx"
)

In [2]:
df = df[
    df['state'] == 'All India'
]

In [3]:
df = df[[
    'year',
    'month',
    'index',
    'inflation'
]]

In [4]:
df.columns = [
    'Year',
    'Month',
    'CPI_Index',
    'Inflation'
]

In [5]:
month_map = {
    'January':'01',
    'February':'02',
    'March':'03',
    'April':'04',
    'May':'05',
    'June':'06',
    'July':'07',
    'August':'08',
    'September':'09',
    'October':'10',
    'November':'11',
    'December':'12'
}

In [6]:
df['MonthNum'] = (
    df['Month']
    .map(month_map)
)

df['Date'] = pd.to_datetime(
    df['Year'].astype(str)
    + '-'
    + df['MonthNum']
    + '-01'
)

In [7]:
numeric_cols = [
    'CPI_Index',
    'Inflation'
]

for col in numeric_cols:

    df[col] = pd.to_numeric(
        df[col],
        errors='coerce'
    )

In [8]:
df = df[[
    'Date',
    'CPI_Index',
    'Inflation'
]]

In [9]:
df.sort_values(
    'Date',
    inplace=True
)

In [10]:
df.reset_index(
    drop=True,
    inplace=True
)

In [11]:
print(df.head())
print(df.info())

        Date  CPI_Index  Inflation
0 2013-01-01       55.1        NaN
1 2013-02-01       55.5        NaN
2 2013-03-01       55.6        NaN
3 2013-04-01       55.9        NaN
4 2013-05-01       56.3        NaN
<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       159 non-null    datetime64[us]
 1   CPI_Index  159 non-null    float64
 2   Inflation  135 non-null    float64
dtypes: datetime64[us](1), float64(2)
memory usage: 3.9 KB
None

In [12]:
df.head()

        Date  CPI_Index  Inflation
0 2013-01-01       55.1        NaN
1 2013-02-01       55.5        NaN
2 2013-03-01       55.6        NaN
3 2013-04-01       55.9        NaN
4 2013-05-01       56.3        NaN

In [14]:
df['Inflation'].isna().sum() / len(df) * 100

15.09433962264151

In [15]:
df['Inflation'] = df['Inflation'].fillna(df['Inflation'].mean())

In [16]:
df.head()

        Date  CPI_Index  Inflation
0 2013-01-01       55.1   5.105778
1 2013-02-01       55.5   5.105778
2 2013-03-01       55.6   5.105778
3 2013-04-01       55.9   5.105778
4 2013-05-01       56.3   5.105778

In [ ]:
df.to_csv(
    r"c:/Users/ka843/Coding/Ruppee-Instability-Dashboard-and-pridictor/data/processed/inflation.csv",
    index=False
)